import { shorthands } from '@griffel/core';

export const supportedShorthandsKeys = Object.keys(shorthands);

// keys of griffel type GriffeltylesUnsupportedCSSProperties, i don't know how to get it as import :/
export const allShorthandsKeys = [
  'animation',
  'background',
  'border',
  'borderBlock',
  'borderBlockEnd',
  'borderBlockStart',
  'borderBottom',
  'borderColor',
  'borderImage',
  'borderInline',
  'borderInlineEnd',
  'borderInlineStart',
  'borderLeft',
  'borderRadius',
  'borderRight',
  'borderStyle',
  'borderTop',
  'borderWidth',
  'columnRule',
  'flex',
  'flexFlow',
  'font',
  'gap',
  'grid',
  'gridArea',
  'gridColumn',
  'gridGap',
  'gridRow',
  'gridTemplate',
  'listStyle',
  'margin',
  'mask',
  'maskBorder',
  'offset',
  'outline',
  'overflow',
  'padding',
  'placeItems',
  'placeSelf',
  'textDecoration',
  'textEmphasis',
  'transition',
];
